# Generated by Django 3.2.10 on 2024-10-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_investment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_return', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_drawdown', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_trades', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
            ],
        ),
        migrations.AddIndex(
            model_name='stockdata',
            index=models.Index(fields=['symbol', 'date'], name='backtester__symbol_930760_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockdata',
            unique_together={('symbol', 'date')},
        ),
    ]
